# syntax=docker/dockerfile:1

FROM --platform=$BUILDPLATFORM alpine:latest
ARG XWIN_VERSION=0.6.5
ARG XWIN_ARCH=x86_64

RUN apk add --no-cache clang lld musl-dev meson cmake ninja pkgconf curl python3 tar git vim

RUN curl --fail -L https://github.com/Jake-Shadle/xwin/releases/download/$XWIN_VERSION/xwin-$XWIN_VERSION-$XWIN_ARCH-unknown-linux-musl.tar.gz \
  | tar -C /usr/local/bin -xzv --wildcards "*/xwin" --strip-components 1
RUN xwin --accept-license splat --output /opt/xwin --include-debug-libs --include-debug-symbols ; rm -rf .xwin-cache

COPY meson/* /usr/local/share/meson/cross/
COPY cmake/* /opt/

